<div class="optimiseweb-system-config-fieldset-hint">

    <a target="_blank" href="<?php echo $this->getOptimiseWebUrl(); ?>"><img src="<?php echo $this->getPxUrl(); ?>" /></a>

    <h4>
        <strong style="color:#ea7601;"><?php echo $this->getModuleName(); ?> v<?php echo $this->getModuleVersion(); ?></strong> by <a target="_blank" href="<?php echo $this->getOptimiseWebUrl(); ?>"><strong>Optimise Web</strong></a> and <a target="_blank" href="<?php echo $this->getKathirVelUrl(); ?>"><strong>Kathir 'Sid' Vel</strong></a>
    </h4>

    <p>
        Need assistance? <a target="_blank" href="<?php echo $this->getHelpDeskUrl(); ?>">Submit a ticket</a>.
        Got feedback? <a target="_blank" href="<?php echo $this->getOptimiseWebEmailLink(); ?>">Email us</a>.
    </p>

</div>

<style>
    .optimiseweb-system-config-fieldset-hint  {
        background: #E7EFEF;
        border: 1px solid #CCCCCC;
        margin-bottom: 10px;
        padding: 11px 0 0 10px;
    }
</style>